### PR TITLE
Add showcase page

### PR DESCRIPTION
**Pull request by thekakamora**
Add a new web page "metricsdao.xyz/showcase" powered by Algolia to surface all analyst submissions

### CODE REVIEW

**Comment by jfmyers** [comment]
Love this! One issue I discovered. 

I was checking out the preview link this PR generated and noticed that the home page styles are messed up. 

Go here: [https://xyz-git-fork-thekakamora-main-metricsdao.vercel.app/](https://xyz-git-fork-thekakamora-main-metricsdao.vercel.app/) and scroll down past the blue section and then do a side-by-side comparison with [https://metricsdao.xyz](https://metricsdao.xyz)

Can you take a look at what's affecting the styles here before we merge?

**Comment by thekakamora** [comment]
@jfmyers thanks for the feedback. I'm investigating the issue.

**Comment by thekakamora** [comment]
@jfmyers tailwindcss was clashing with bootstrap classes. To resolve the issue I prefixed all tailwind generated classes with `tw-`.  
The other alternate option I thought about is to rebuild the home page with tailwindcss and completely remove bootstrap from app. Considering the time it requires and other priorities I leaned towards prefixing all tailwindcss classes. please let me know your thoghts.

**Comment by addyxvii** [comment]
> @jfmyers tailwindcss was clashing with bootstrap classes. To resolve the issue I prefixed all tailwind generated classes with `tw-`. The other alternate option I thought about is to rebuild the home page with tailwindcss and completely remove bootstrap from app. Considering the time it requires and other priorities I leaned towards prefixing all tailwindcss classes. please let me know your thoghts.

Ideally we would remove bootstrap since it's an anti-pattern to have multiple Frameworks. That being said I don't have context on why we're using bootstrap. My opinion; if it's similar amount of work to prefix tailwind classes and remove bootstrap, I would say remove bootstrap.

**Comment by jdaly13** [comment]
> > @jfmyers tailwindcss was clashing with bootstrap classes. To resolve the issue I prefixed all tailwind generated classes with `tw-`. The other alternate option I thought about is to rebuild the home page with tailwindcss and completely remove bootstrap from app. Considering the time it requires and other priorities I leaned towards prefixing all tailwindcss classes. please let me know your thoghts.
> 
> Ideally we would remove bootstrap since it's an anti-pattern to have multiple Frameworks. That being said I don't have context on why we're using bootstrap. My opinion; if it's similar amount of work to prefix tailwind classes and remove bootstrap, I would say remove bootstrap.

I second this as well, let's remove bootstrap as I think it will only complicate things down the line

**Comment by thekakamora** [comment]
@addyxvii  I think the effort to rebuild the home page with tailwindcss is not trivial (btw I'm not a HTML / CSS proficient) and requires someone with proficient skills to look at this and scope the task. 

On the other hand, prefixing tailwindcss with `tw-` was a simple configuration change I could do it myself. The change is part of the PR. 

Here are the two options I see we have now. Please let me know if there any other approaches we can take
1. Leave home page with bootstrap for now and continue using tailwind with showcase page (or any new page we build from now onwards) and plan to rewrite once @drakedanner / catjam hires a web dev expert. This will help us to launch the `showcase` page. Community has been waiting for a long time! 
2. Hold this PR till we find someone who can rewrite homepage with tailwindcss

I suggest we go with option 1, though I'm not a big fan of mixing multiple css frameworks in a single project. We should plan to get rid of bootstrap slowly while allowing new development with tailwindcss. 

But I let you  take the call.

**Comment by addyxvii** [comment]
@thekakamora 

I agree with you option 1 is good to keep things moving.

**Pull request merged**
