### PR TITLE
Added tags and removed redundant program name on showcase page

### PR DESCRIPTION
**Pull request by D0R11**
This PR fixes issue #16. Added tags on the program name beside the submission title and made the whole section a hyperlink redirecting to the dashboard.

### CODE REVIEW

**Comment by thekakamora** [comment]
Errors while deploying to test server...

image

**Comment by thekakamora** [comment]
@D0R11  couple of observations 
1. Isn't the lables redundant when we have a logo? Shall we remove labels and just keep the logos? What you think? Tagging @drakedanner to get his opinion also.
2. Please use a fallback, generic logo for program that we you don't recognize. For example, we refreshed data to include "messari" submissions. in showcase page and they don't show a logo. 
3. What you think of showing program name as a mouse over text on "logo" image. This will be helpful when we use a fallback/generic logo for programs that does not have logos.

**Comment by thekakamora** [comment]
@D0R11  I deployed your fix to a preview server. And here are few observations, I think we should close this PR as soon as possible. I'll play my part in reviewing this soon and close it. 

1. I personally like the logos and not the tags. If you agree, please remove the tags
2. Your git branch seems to be behind. Please get the latest and make sure your branch is up-to date. I see the the issue fixed in https://github.com/MetricsDAO/xyz/pull/29 resurfacing on the deployment.

**Comment by D0R11** [comment]
> @D0R11 I deployed your fix to a preview server. And here are few observations, I think we should close this PR as soon as possible. I'll play my part in reviewing this soon and close it.
> 
> 1. I personally like the logos and not the tags. If you agree, please remove the tags
> 2. Your git branch seems to be behind. Please get the latest and make sure your branch is up-to date. I see the the issue fixed in [fix (showcase) @ #14: updating margin styles to optimize mobile ui #29](https://github.com/MetricsDAO/xyz/pull/29) resurfacing on the deployment.

Done. Updated the branch resolving the conflicts and removed the tags.

**Pull request merged**
