### PR TITLE
PD-61 update sort by selection

### PR DESCRIPTION
**Pull request by termaatFlipside**

### CODE REVIEW

**Comment by jdaly13** [comment]
Hi @termaatFlipside  - can you resolve the conflicts and push again and also remove draft status if it's ready to review
I pulled the branch and the functionality seemed to be working but had some styling issues
Screen Shot 2022-09-15 at 2 56 50 PM

**Comment by jdaly13** [comment]
Screen Shot 2022-09-16 at 10 52 03 AM
Looks updated but missing a section for program for the Filtering 
Here's the designs

**Comment by jdaly13** [comment]
Also you need to pull from latest and fix any merge conflicts as well

**Comment by jdaly13** [comment]
Also when one hovers over the checkbox you should probably still get a cursor as well

**Comment by jdaly13** [comment]
Thanks for making those changes @termaatFlipside  - this looks good to me @thehannahlerman - can you take a look at this as well I wasn't sure how these changes affect your work

**Review by thehannahlerman — APPROVED** [review]
LGTM

**Pull request merged**
